[package]
name = "firmware-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "firmware-explorer"
path = "src/main.rs"

[dependencies]
firmware-analysis-core.workspace = true
serde.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive"] }

