//! Read Windows Installer ownership, without launching or modifying an installer.

use std::path::{Path, PathBuf};

// Keep in sync with wix/main.wxs. Product and component IDs are generated by WiX.
const UPGRADE_CODE: &str = "{A62F6D56-6973-4C6D-ACD8-4599E331C313}";

fn owns_executable<T>(
    executable: &Path,
    products: &[T],
    mut component: impl FnMut(u32) -> Result<Option<T>, String>,
    mut component_path: impl FnMut(&T, &T) -> Result<Option<PathBuf>, String>,
) -> Result<bool, String> {
    if products.is_empty() {
        return Ok(false);
    }
    let executable = executable.canonicalize().map_err(|e| e.to_string())?;
    let mut index = 0;
    while let Some(id) = component(index)? {
        for product in products {
            if let Some(path) = component_path(product, &id)? {
                if path.canonicalize().is_ok_and(|path| path == executable) {
                    return Ok(true);
                }
            }
        }
        index += 1;
    }
    Ok(false)
}

#[cfg(windows)]
pub(super) fn installed() -> Result<bool, String> {
    let executable = std::env::current_exe().map_err(|e| e.to_string())?;
    installed_at(&executable)
}

#[cfg(windows)]
fn installed_at(executable: &Path) -> Result<bool, String> {
    use std::ffi::OsString;
    use std::os::windows::ffi::OsStringExt;

    #[link(name = "msi")]
    extern "system" {
        fn MsiEnumRelatedProductsW(
            upgrade: *const u16,
            reserved: u32,
            index: u32,
            product: *mut u16,
        ) -> u32;
        fn MsiEnumComponentsW(index: u32, component: *mut u16) -> u32;
        fn MsiEnumClientsW(component: *const u16, index: u32, product: *mut u16) -> u32;
        fn MsiGetComponentPathW(
            product: *const u16,
            component: *const u16,
            path: *mut u16,
            length: *mut u32,
        ) -> i32;
    }

    fn enumerated(status: u32, id: [u16; 39]) -> Result<Option<[u16; 39]>, String> {
        match status {
            0 => Ok(Some(id)),
            259 => Ok(None), // ERROR_NO_MORE_ITEMS
            other => Err(format!(
                "Windows Installer ownership lookup failed ({other})."
            )),
        }
    }

    let upgrade: Vec<u16> = UPGRADE_CODE.encode_utf16().chain(Some(0)).collect();
    let mut products = Vec::new();
    loop {
        let mut id = [0; 39];
        // SAFETY: the GUID input is NUL terminated and the output has the
        // documented 39 UTF-16 code units. Enumeration stays on this thread.
        let status = unsafe {
            MsiEnumRelatedProductsW(upgrade.as_ptr(), 0, products.len() as u32, id.as_mut_ptr())
        };
        match enumerated(status, id)? {
            Some(id) => products.push(id),
            None => break,
        }
    }
    owns_executable(
        executable,
        &products,
        |index| {
            let mut id = [0; 39];
            // SAFETY: the output is a correctly sized GUID buffer.
            let status = unsafe { MsiEnumComponentsW(index, id.as_mut_ptr()) };
            enumerated(status, id)
        },
        |product, component| {
            // A component can be shared. Confirm this product is a registered
            // client before considering its key path as ownership evidence.
            let mut index = 0;
            loop {
                let mut client = [0; 39];
                // SAFETY: component is a NUL-terminated GUID and client has
                // the documented 39 code units. Enumeration stays on one thread.
                let status =
                    unsafe { MsiEnumClientsW(component.as_ptr(), index, client.as_mut_ptr()) };
                match enumerated(status, client)? {
                    Some(client)
                        if String::from_utf16_lossy(&client)
                            .eq_ignore_ascii_case(&String::from_utf16_lossy(product)) =>
                    {
                        break
                    }
                    Some(_) => index += 1,
                    None => return Ok(None),
                }
            }
            let mut path = vec![0; 260];
            loop {
                let mut length = path.len() as u32;
                // SAFETY: both GUIDs are NUL terminated; length describes the
                // writable buffer and all pointers remain valid during the call.
                let state = unsafe {
                    MsiGetComponentPathW(
                        product.as_ptr(),
                        component.as_ptr(),
                        path.as_mut_ptr(),
                        &mut length,
                    )
                };
                match state {
                    -3 => path.resize(length as usize + 1, 0), // INSTALLSTATE_MOREDATA
                    3 | 4 => {
                        return Ok(Some(PathBuf::from(OsString::from_wide(
                            &path[..length as usize],
                        ))))
                    }
                    // Unknown components belong to other products. Absent,
                    // disabled, or unavailable components cannot own this image.
                    -7 | -1 | 0 | 1 | 2 => return Ok(None),
                    other => {
                        return Err(format!(
                            "Windows Installer component lookup failed ({other})."
                        ))
                    }
                }
            }
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn upgrade_code_matches_the_shipped_installer() {
        assert!(include_str!("../wix/main.wxs").contains(&format!(
            "UpgradeCode=\"{}\"",
            UPGRADE_CODE.trim_matches(['{', '}'])
        )));
    }

    #[test]
    fn ownership_requires_this_products_exact_executable() {
        let dir = tempfile::tempdir().unwrap();
        let installed = dir.path().join("msi/firmware-gui.exe");
        let portable = dir.path().join("portable/firmware-gui.exe");
        let setup_user = dir.path().join("setup-user/firmware-gui.exe");
        let setup_machine = dir.path().join("setup-machine/firmware-gui.exe");
        for path in [&installed, &portable, &setup_user, &setup_machine] {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(path, b"image").unwrap();
        }
        for (image, expected) in [
            (&installed, true),
            (&portable, false),
            (&setup_user, false),
            (&setup_machine, false),
        ] {
            let owned = owns_executable(
                image,
                &[42],
                |index| Ok((index < 2).then_some(index)),
                |product, component| {
                    assert_eq!(*product, 42);
                    Ok((*component == 1).then(|| installed.clone()))
                },
            )
            .unwrap();
            assert_eq!(owned, expected);
        }
        assert!(!owns_executable(
            &installed,
            &[],
            |_| Ok(Some(0)),
            |_, _| Ok(Some(installed.clone()))
        )
        .unwrap());
        assert!(owns_executable(
            &installed,
            &[42],
            |_| Err("registry failure".into()),
            |_, _| Ok(None)
        )
        .is_err());
        assert!(owns_executable(
            &installed,
            &[42],
            |_| Ok(Some(0)),
            |_, _| Err("component failure".into())
        )
        .is_err());
    }

    #[cfg(windows)]
    #[test]
    fn native_ownership_matches_the_integration_environment() {
        // Probe an installed production binary without replacing its registered
        // component with a test binary. Ordinary test binaries are unowned.
        let expected = std::env::var("SNOUT_EXPECT_MSI").is_ok_and(|v| v == "1");
        let image = std::env::var_os("SNOUT_MSI_EXECUTABLE")
            .map(PathBuf::from)
            .unwrap_or_else(|| std::env::current_exe().unwrap());
        assert_eq!(installed_at(&image).unwrap(), expected);
    }
}
