//! Read Windows Installer ownership, without launching or modifying an installer.

use std::path::{Path, PathBuf};

// Keep in sync with wix/main.wxs. Product and component IDs are generated by WiX.
const UPGRADE_CODE: &str = "{A62F6D56-6973-4C6D-ACD8-4599E331C313}";

fn owns_executable<T>(
    executable: &Path,
    products: &[T],
    mut component: impl FnMut(u32) -> Result<Option<T>, String>,
    mut component_path: impl FnMut(&T, &T) -> Result<Option<PathBuf>, String>,
) -> Result<bool, String> {
    if products.is_empty() {
        return Ok(false);
    }
    let executable = same_file::Handle::from_path(executable).map_err(|e| e.to_string())?;
    let mut lookup_error = None;
    let mut index = 0;
    while let Some(id) = component(index)? {
        for product in products {
            let path = match component_path(product, &id) {
                Ok(path) => path,
                Err(error) => {
                    lookup_error.get_or_insert(error);
                    continue;
                }
            };
            if let Some(path) = path {
                // MSI also returns registry key paths (for example, "02:\\...").
                // Only absolute filesystem paths can own the running image.
                if !path.is_absolute() {
                    continue;
                }
                // Preserve uncertainty, but keep looking: a missing license
                // must not mask a later confirmed executable component.
                // Compare file identity, not path spelling: Windows volume
                // aliases and hard links can resolve to the same running image
                // while still having different canonical paths.
                let resolved = match same_file::Handle::from_path(&path) {
                    Ok(resolved) => resolved,
                    Err(error) => {
                        lookup_error.get_or_insert_with(|| {
                            format!(
                                "Windows Installer component path lookup failed for {}: {error}.",
                                path.display()
                            )
                        });
                        continue;
                    }
                };
                if resolved == executable {
                    return Ok(true);
                }
            }
        }
        index += 1;
    }
    // An unresolved registered file is not evidence that this copy is portable.
    match lookup_error {
        Some(error) => Err(error),
        None => Ok(false),
    }
}

// Interpret native states separately so the fail-closed policy is tested on
// every platform, even when the Windows Installer API is unavailable.
fn component_has_path(state: i32) -> Result<bool, String> {
    match state {
        3 | 4 => Ok(true), // INSTALLSTATE_LOCAL / INSTALLSTATE_SOURCE
        // Unknown, disabled, advertised, or absent components have no
        // installed path. BROKEN (0) is uncertainty, not proof of no owner.
        -7 | -1 | 1 | 2 => Ok(false),
        other => Err(format!(
            "Windows Installer component lookup failed ({other})."
        )),
    }
}

#[cfg(windows)]
pub(super) fn installed() -> Result<bool, String> {
    let executable = std::env::current_exe().map_err(|e| e.to_string())?;
    installed_at(&executable)
}

#[cfg(windows)]
fn installed_at(executable: &Path) -> Result<bool, String> {
    use std::ffi::OsString;
    use std::os::windows::ffi::OsStringExt;

    #[link(name = "msi")]
    extern "system" {
        fn MsiEnumRelatedProductsW(
            upgrade: *const u16,
            reserved: u32,
            index: u32,
            product: *mut u16,
        ) -> u32;
        fn MsiEnumComponentsW(index: u32, component: *mut u16) -> u32;
        fn MsiEnumClientsW(component: *const u16, index: u32, product: *mut u16) -> u32;
        fn MsiGetComponentPathW(
            product: *const u16,
            component: *const u16,
            path: *mut u16,
            length: *mut u32,
        ) -> i32;
    }

    fn enumerated(status: u32, id: [u16; 39]) -> Result<Option<[u16; 39]>, String> {
        match status {
            0 => Ok(Some(id)),
            259 => Ok(None), // ERROR_NO_MORE_ITEMS
            other => Err(format!(
                "Windows Installer ownership lookup failed ({other})."
            )),
        }
    }

    let upgrade: Vec<u16> = UPGRADE_CODE.encode_utf16().chain(Some(0)).collect();
    let mut products = Vec::new();
    loop {
        let mut id = [0; 39];
        // SAFETY: the GUID input is NUL terminated and the output has the
        // documented 39 UTF-16 code units. Enumeration stays on this thread.
        let status = unsafe {
            MsiEnumRelatedProductsW(upgrade.as_ptr(), 0, products.len() as u32, id.as_mut_ptr())
        };
        match enumerated(status, id)? {
            Some(id) => products.push(id),
            None => break,
        }
    }
    owns_executable(
        executable,
        &products,
        |index| {
            let mut id = [0; 39];
            // SAFETY: the output is a correctly sized GUID buffer.
            let status = unsafe { MsiEnumComponentsW(index, id.as_mut_ptr()) };
            enumerated(status, id)
        },
        |product, component| {
            // A component can be shared. Confirm this product is a registered
            // client before considering its key path as ownership evidence.
            let mut index = 0;
            loop {
                let mut client = [0; 39];
                // SAFETY: component is a NUL-terminated GUID and client has
                // the documented 39 code units. Enumeration stays on one thread.
                let status =
                    unsafe { MsiEnumClientsW(component.as_ptr(), index, client.as_mut_ptr()) };
                match enumerated(status, client)? {
                    Some(client)
                        if String::from_utf16_lossy(&client)
                            .eq_ignore_ascii_case(&String::from_utf16_lossy(product)) =>
                    {
                        break
                    }
                    Some(_) => index += 1,
                    None => return Ok(None),
                }
            }
            let mut path = vec![0; 260];
            loop {
                let mut length = path.len() as u32;
                // SAFETY: both GUIDs are NUL terminated; length describes the
                // writable buffer and all pointers remain valid during the call.
                let state = unsafe {
                    MsiGetComponentPathW(
                        product.as_ptr(),
                        component.as_ptr(),
                        path.as_mut_ptr(),
                        &mut length,
                    )
                };
                match state {
                    -3 => path.resize(length as usize + 1, 0), // INSTALLSTATE_MOREDATA
                    other => {
                        return if component_has_path(other)? {
                            Ok(Some(PathBuf::from(OsString::from_wide(
                                &path[..length as usize],
                            ))))
                        } else {
                            Ok(None)
                        };
                    }
                }
            }
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn broken_registered_component_blocks_replacement_unless_owner_is_confirmed() {
        let dir = tempfile::tempdir().unwrap();
        let executable = dir.path().join("firmware-gui.exe");
        std::fs::write(&executable, b"image").unwrap();
        for confirmed in [false, true] {
            let result = owns_executable(
                &executable,
                &[42],
                |index| Ok((index < 2).then_some(index)),
                |_, component| {
                    if *component == 0 {
                        component_has_path(0).map(|_| None) // INSTALLSTATE_BROKEN
                    } else {
                        Ok(confirmed.then(|| executable.clone()))
                    }
                },
            );
            if confirmed {
                assert_eq!(result, Ok(true));
            } else {
                assert!(
                    result.is_err(),
                    "broken registration must not permit replacement"
                );
            }
        }
    }

    #[test]
    fn upgrade_code_matches_the_shipped_installer() {
        assert!(include_str!("../wix/main.wxs").contains(&format!(
            "UpgradeCode=\"{}\"",
            UPGRADE_CODE.trim_matches(['{', '}'])
        )));
    }

    #[test]
    fn ownership_requires_this_products_exact_executable() {
        let dir = tempfile::tempdir().unwrap();
        let installed = dir.path().join("msi/firmware-gui.exe");
        let portable = dir.path().join("portable/firmware-gui.exe");
        let setup_user = dir.path().join("setup-user/firmware-gui.exe");
        let setup_machine = dir.path().join("setup-machine/firmware-gui.exe");
        for path in [&installed, &portable, &setup_user, &setup_machine] {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(path, b"image").unwrap();
        }
        for (image, expected) in [
            (&installed, true),
            (&portable, false),
            (&setup_user, false),
            (&setup_machine, false),
        ] {
            let owned = owns_executable(
                image,
                &[42],
                |index| Ok((index < 2).then_some(index)),
                |product, component| {
                    assert_eq!(*product, 42);
                    Ok((*component == 1).then(|| installed.clone()))
                },
            )
            .unwrap();
            assert_eq!(owned, expected);
        }
        assert!(!owns_executable(
            &installed,
            &[],
            |_| Ok(Some(0)),
            |_, _| Ok(Some(installed.clone()))
        )
        .unwrap());
        assert!(owns_executable(
            &installed,
            &[42],
            |_| Err("registry failure".into()),
            |_, _| Ok(None)
        )
        .is_err());
        assert!(owns_executable(
            &installed,
            &[42],
            |index| Ok((index == 0).then_some(0)),
            |_, _| Err("component failure".into())
        )
        .is_err());
    }

    #[test]
    fn executable_alias_is_owned_but_an_independent_copy_is_not() {
        let dir = tempfile::tempdir().unwrap();
        let registered = dir.path().join("firmware-gui.exe");
        let alias = dir.path().join("alias.exe");
        let copy = dir.path().join("portable.exe");
        std::fs::write(&registered, b"image").unwrap();
        std::fs::hard_link(&registered, &alias).unwrap();
        std::fs::copy(&registered, &copy).unwrap();
        assert_ne!(
            registered.canonicalize().unwrap(),
            alias.canonicalize().unwrap()
        );
        for (image, expected) in [(&alias, true), (&copy, false)] {
            assert_eq!(
                owns_executable(
                    image,
                    &[42],
                    |index| Ok((index == 0).then_some(0)),
                    |_, _| Ok(Some(registered.clone())),
                ),
                Ok(expected)
            );
        }
    }

    #[test]
    fn missing_license_does_not_mask_registered_executable() {
        let dir = tempfile::tempdir().unwrap();
        let executable = dir.path().join("firmware-gui.exe");
        std::fs::write(&executable, b"image").unwrap();
        let missing = dir.path().join("License.rtf");
        // MSI component enumeration has no guaranteed order. A damaged
        // ancillary component must not hide positive executable ownership.
        for missing_first in [false, true] {
            let result = owns_executable(
                &executable,
                &[42],
                |index| Ok((index < 2).then_some(index)),
                |_, component| {
                    Ok(Some(if (*component == 0) == missing_first {
                        missing.clone()
                    } else {
                        executable.clone()
                    }))
                },
            );
            assert_eq!(result, Ok(true));
        }
    }

    #[test]
    fn failed_component_lookup_does_not_mask_confirmed_ownership() {
        let dir = tempfile::tempdir().unwrap();
        let executable = dir.path().join("firmware-gui.exe");
        std::fs::write(&executable, b"image").unwrap();
        assert_eq!(
            owns_executable(
                &executable,
                &[42],
                |index| Ok((index < 2).then_some(index)),
                |_, component| {
                    if *component == 0 {
                        Err("component failure".into())
                    } else {
                        Ok(Some(executable.clone()))
                    }
                },
            ),
            Ok(true)
        );
    }

    #[test]
    fn unresolved_registered_file_blocks_replacement() {
        let dir = tempfile::tempdir().unwrap();
        let executable = dir.path().join("firmware-gui.exe");
        std::fs::write(&executable, b"image").unwrap();
        let missing = dir.path().join("inaccessible/firmware-gui.exe");
        let result = owns_executable(
            &executable,
            &[42],
            |index| Ok((index == 0).then_some(0)),
            |_, _| Ok(Some(missing.clone())),
        );
        assert!(result.unwrap_err().contains("component path lookup failed"));
    }

    #[test]
    fn registry_key_paths_do_not_mask_executable_ownership() {
        let dir = tempfile::tempdir().unwrap();
        let executable = dir.path().join("firmware-gui.exe");
        std::fs::write(&executable, b"image").unwrap();
        for owned in [false, true] {
            assert_eq!(
                owns_executable(
                    &executable,
                    &[42],
                    |index| Ok((index < 2).then_some(index)),
                    |_, component| Ok(match component {
                        0 => Some(PathBuf::from(r"02:\SOFTWARE\Snout")),
                        _ if owned => Some(executable.clone()),
                        _ => None,
                    }),
                )
                .unwrap(),
                owned
            );
        }
    }

    #[cfg(windows)]
    #[test]
    fn native_ownership_matches_the_integration_environment() {
        // Probe an installed production binary without replacing its registered
        // component with a test binary. Ordinary test binaries are unowned.
        let expected = std::env::var("SNOUT_EXPECT_MSI").is_ok_and(|v| v == "1");
        let image = std::env::var_os("SNOUT_MSI_EXECUTABLE")
            .map(PathBuf::from)
            .unwrap_or_else(|| std::env::current_exe().unwrap());
        assert_eq!(installed_at(&image).unwrap(), expected);
    }
}
